services:
  server:
    build: .
    env_file:
      - ./server/.env
    ports:
      - 5000:5000
    stop_grace_period: 1s
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    command: npm run dev-server