name: Deploy to AWS

on:
  push:
    branches: ['deploy-aws']

jobs:
  build:
    name: Build Docker image and push to Amazon ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t 454158562433.dkr.ecr.us-east-1.amazonaws.com/ruruflashcards .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to Amazon ECR
        run: docker push 454158562433.dkr.ecr.us-east-1.amazonaws.com/ruruflashcards:latest

  deploy:
    name: Pull Docker image and run container inside EC2 instance
    needs: build
    runs-on: ruruflashcards-ec2
    steps:
      - name: Pull Docker image
        run: docker pull 454158562433.dkr.ecr.us-east-1.amazonaws.com/ruruflashcards:latest

      - name: Stop and delete previous Docker container
        run: docker rm -f ruruflashcards-server

      - name: Run new Docker container
        run: >
          docker run -d -p 80:5000 -p 443:5000
          --env-file ~/ruruflashcards-env-file
          --name ruruflashcards-server
          454158562433.dkr.ecr.us-east-1.amazonaws.com/ruruflashcards:latest
