name: Deploy to AWS

on:
  push:
    branches: ['deploy-aws']

jobs:
  build:
    name: Build Docker image and push to Amazon ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t 454158562433.dkr.ecr.us-east-1.amazonaws.com/ruruflashcards .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login Docker to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to Amazon ECR
        run: docker push 454158562433.dkr.ecr.us-east-1.amazonaws.com/ruruflashcards:latest

  deploy:
    name: Pull Docker image and run container inside EC2 instance
    needs: build
    runs-on: ruruflashcards-ec2
    steps:
      - name: Login Docker to Amazon ECR
        run: >
          aws ecr get-login-password --region us-east-1 |
          docker login --username AWS --password-stdin
          454158562433.dkr.ecr.us-east-1.amazonaws.com

      - name: Pull Docker image
        run: docker pull 454158562433.dkr.ecr.us-east-1.amazonaws.com/ruruflashcards:latest

      - name: Stop and delete previous Docker containers and images
        run: |
          docker stop ruruflashcards-server --time 0
          docker container prune -f
          docker image prune -f

      - name: Run new Docker container
        run: >
          docker run -d -p 80:5000 -p 443:5000
          --name ruruflashcards-server
          --env GOOGLE_CLOUD_CREDENTIALS="$(aws ssm get-parameter --name /ruruflashcards/google-cloud-credentials | jq -r '.Parameter.Value')"
          --env MONGODB_URI="$(aws ssm get-parameter --name /ruruflashcards/mongodb-uri | jq -r '.Parameter.Value')"
          --env SESSION_SECRET="$(aws ssm get-parameter --name /ruruflashcards/session-secret | jq -r '.Parameter.Value')"
          454158562433.dkr.ecr.us-east-1.amazonaws.com/ruruflashcards:latest
